sonar.projectKey=ha-ulkovalot
sonar.projectName=ha-ulkovalot

sonar.sources=custom_components/ulkovalot
sonar.tests=tests

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/__pycache__/**,**/.venv/**,.dev/**
sonar.coverage.exclusions=tests/**,custom_components/ulkovalot/__init__.py

sonar.sourceEncoding=UTF-8
